name = "DFT-raMO"
uuid = "90d47691-e9bb-4225-9ddc-87e73db60b62"
authors = ["Amber Lim <xalim@wisc.edu>", "Brandon Flores <bsflores@wisc.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
